/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc mainInstanced.vert -o ../Resources/Shaders/vertMainInstanced.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc mainOnce.vert -o ../Resources/Shaders/vertMainOnce.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc main.frag -o ../Resources/Shaders/fragMain.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc hud.vert -o ../Resources/Shaders/vertHud.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc hud.frag -o ../Resources/Shaders/fragHud.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc shadowInstanced.vert -o ../Resources/Shaders/vertShadowInstanced.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc shadowOnce.vert -o ../Resources/Shaders/vertShadowOnce.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc skybox.vert -o ../Resources/Shaders/vertSkybox.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc skybox.frag -o ../Resources/Shaders/fragSkybox.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc final.vert -o ../Resources/Shaders/vertFinal.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc final.frag -o ../Resources/Shaders/fragFinal.spv
/Users/eprager/VulkanSDK/1.3.250.0/macOS/bin/glslc histogram.comp -o ../Resources/Shaders/histogram.spv
